# Generated by Django 5.1 on 2026-04-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_instances', to='orgs.branch'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='business_date',
            field=models.DateField(blank=True, null=True, verbose_name='Business date'),
        ),
    ]
